version: '3'

services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: arma
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - "db-data:/var/lib/mysql"
      - "./docker/mysql/my.conf:/etc/mysql/my.conf"
      - "./docker/mysql/conf.d:/etc/mysql/conf.d"
      - "./docker/mysql/init/:/docker-entrypoint-initdb.d"

  app:
    links:
      - mysql
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app

volumes:
  db-data:
    driver: local
